egov:
  enabled: true
  keywords:
    - 法人税法
    - 所得税法
    - 消費税法
    - 相続税法
    - 国税通則法
    - 国税徴収法
    - 租税特別措置法
    - 印紙税法
    - 地方税法
    - 税理士法
    - 会社法
    - 会社法施行規則
    - 会社計算規則
    - 商業登記法
    - 商業登記規則
    - 労働基準法
    - 健康保険法
    - 厚生年金保険法
    - 雇用保険法
    - 労働保険の保険料の徴収等に関する法律
    - 減価償却資産の耐用年数等に関する省令
    - 登録免許税法
    - 民法
    - 建築基準法
  max_laws: 200

nta:
  enabled: true
  max_pages: 3000
  delay_seconds: 0.6
  seeds:
    # 基本通達：法人税
    - https://www.nta.go.jp/law/tsutatsu/kihon/hojin/01.htm
    # 基本通達：所得税
    - https://www.nta.go.jp/law/tsutatsu/kihon/shotoku/01.htm
    # 基本通達：消費税
    - https://www.nta.go.jp/law/tsutatsu/kihon/shohi/01.htm
    # 基本通達：印紙税
    - https://www.nta.go.jp/law/tsutatsu/kihon/inshi/mokuji.htm
    # 基本通達：国税通則法（徴収部）
    - https://www.nta.go.jp/law/tsutatsu/kihon/tsusoku/00.htm
    # 基本通達：国税徴収法
    - https://www.nta.go.jp/law/tsutatsu/kihon/chosyu/index.htm
    # 基本通達：相続税法（※この中に贈与税の基本通達も入ってる）
    - https://www.nta.go.jp/law/tsutatsu/kihon/sisan/sozoku2/01.htm
    # 基本通達：財産評価
    - https://www.nta.go.jp/law/tsutatsu/kihon/sisan/hyoka_new/01.htm

  allowed_prefixes:
    - https://www.nta.go.jp/law/tsutatsu/kihon/

  exclude_url_regex:
    - "/kaisei/"
    - "/pdf/"
    - "\\.pdf$"



chunking:
  max_chars: 1200
  overlap_chars: 200

embedding:
  model: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
  normalize: true
