egov:
  enabled: true
  keywords:
    - 法人税法
    - 所得税法
    - 消費税法
    - 相続税法
    - 国税通則法
    - 国税徴収法
    - 租税特別措置法
    - 印紙税法
    - 地方税法
    - 税理士法
    - 会社法
    - 会社法施行規則
    - 会社計算規則
    - 商業登記法
    - 商業登記規則
    - 労働基準法
    - 健康保険法
    - 厚生年金保険法
    - 雇用保険法
    - 労働保険の保険料の徴収等に関する法律
    - 減価償却資産の耐用年数等に関する省令
    - 登録免許税法
    - 民法
    - 建築基準法
  max_laws: 200

nta:
  enabled: true
  max_pages: 3000
  delay_seconds: 0.6
  seeds:
    # 基本通達：法人税
    - https://www.nta.go.jp/law/tsutatsu/kihon/hojin/01.htm
    # 基本通達：所得税
    - https://www.nta.go.jp/law/tsutatsu/kihon/shotoku/01.htm
    # 基本通達：消費税
    - https://www.nta.go.jp/law/tsutatsu/kihon/shohi/01.htm
    # 基本通達：印紙税
    - https://www.nta.go.jp/law/tsutatsu/kihon/inshi/mokuji.htm
    # 基本通達：国税通則法（徴収部）
    - https://www.nta.go.jp/law/tsutatsu/kihon/tsusoku/00.htm
    # 基本通達：国税徴収法
    - https://www.nta.go.jp/law/tsutatsu/kihon/chosyu/index.htm
    # 基本通達：相続税法（※この中に贈与税の基本通達も入ってる）
    - https://www.nta.go.jp/law/tsutatsu/kihon/sisan/sozoku2/01.htm
    # 基本通達：財産評価
    - https://www.nta.go.jp/law/tsutatsu/kihon/sisan/hyoka_new/01.htm

  allowed_prefixes:
    - https://www.nta.go.jp/law/tsutatsu/kihon/

  exclude_url_regex:
    - "/kaisei/"
    - "/pdf/"
    - "\\.pdf$"

  skip_save_title_regex:
    - "目次"
    - "一覧"
  skip_save_url_regex:
    - "/mokuji\\.htm"
    - "/index\\.htm"

nta_sochiho:
  enabled: true
  max_pages: 2500
  delay_seconds: 0.6
  seeds:
    - https://www.nta.go.jp/law/tsutatsu/kobetsu/hojin/sochiho/sotihou.htm
    - https://www.nta.go.jp/law/tsutatsu/kobetsu/shotoku/sochiho/sotihou.htm
    - https://www.nta.go.jp/law/tsutatsu/kobetsu/kansetsu/sochiho/sotihou.htm
    - https://www.nta.go.jp/law/tsutatsu/kobetsu/sozoku/sochiho/sotihou.htm
    - https://www.nta.go.jp/law/tsutatsu/kobetsu/sonota/sochiho/sotihou.htm

  allowed_prefixes:
    - https://www.nta.go.jp/law/tsutatsu/kobetsu/hojin/sochiho/
    - https://www.nta.go.jp/law/tsutatsu/kobetsu/shotoku/sochiho/
    - https://www.nta.go.jp/law/tsutatsu/kobetsu/kansetsu/sochiho/
    - https://www.nta.go.jp/law/tsutatsu/kobetsu/sozoku/sochiho/
    - https://www.nta.go.jp/law/tsutatsu/kobetsu/sonota/sochiho/

  exclude_url_regex:
    - "/kaisei/"
    - "/pdf/"
    - "\\.pdf$"

nta_shitsugi:
  enabled: true
  max_pages: 2000
  delay_seconds: 0.6
  seeds:
    - https://www.nta.go.jp/law/shitsugi/01.htm
  allowed_prefixes:
    - https://www.nta.go.jp/law/shitsugi/
  exclude_url_regex:
    - "/pdf/"
    - "\\.pdf$"
  skip_save_title_regex:
    - "目次"
    - "一覧"
  skip_save_url_regex:
    - "/index\\.htm"

taxanswer:
  enabled: true
  max_pages: 20000
  delay_seconds: 0.6
  seeds:
    - https://www.nta.go.jp/taxes/shiraberu/taxanswer/index2.htm
    - https://www.nta.go.jp/taxes/shiraberu/taxanswer/code/index.htm
  allowed_prefixes:
    - https://www.nta.go.jp/taxes/shiraberu/taxanswer/
  exclude_url_regex:
    - "/pdf/"
    - "\\.pdf$"
  skip_save_title_regex:
    - "一覧"
  skip_save_url_regex:
    - "/index\\.htm"
    - "/index2\\.htm"

nta_kobetsu:
  enabled: true
  max_pages: 50000
  delay_seconds: 0.6

  # 個別通達「目次」ページ（ここから全部辿る）
  seeds:
    - https://www.nta.go.jp/law/tsutatsu/kobetsu/hojin/houzin.htm          # 法人税関係 個別通達目次 :contentReference[oaicite:0]{index=0}
    - https://www.nta.go.jp/law/tsutatsu/kobetsu/shotoku/shinkoku/sinkoku.htm # 申告所得税関係 個別通達目次 :contentReference[oaicite:1]{index=1}
    - https://www.nta.go.jp/law/tsutatsu/kobetsu/shotoku/gensen/gensen.htm    # 源泉所得税関係 個別通達目次 :contentReference[oaicite:2]{index=2}
    - https://www.nta.go.jp/law/tsutatsu/kobetsu/kansetsu/syouhi.htm      # 間接税関係 個別通達目次 :contentReference[oaicite:3]{index=3}
    - https://www.nta.go.jp/law/tsutatsu/kobetsu/sozoku/souzoku.htm       # 相続税関係 個別通達目次 :contentReference[oaicite:4]{index=4}
    - https://www.nta.go.jp/law/tsutatsu/kobetsu/hyoka/zaisan.htm         # 財産評価関係 個別通達目次 :contentReference[oaicite:5]{index=5}
    - https://www.nta.go.jp/law/tsutatsu/kobetsu/zeimuchosa/zeimuchosa.htm # 税務調査手続関係 個別通達目次 :contentReference[oaicite:6]{index=6}
    - https://www.nta.go.jp/law/tsutatsu/kobetsu/sonota/sonota.htm        # その他 個別通達目次 :contentReference[oaicite:7]{index=7}

  allowed_prefixes:
    - https://www.nta.go.jp/law/tsutatsu/kobetsu/

  # PDFなどは今は除外（HTML本文だけ先にRAGへ）
  exclude_url_regex:
    - "/pdf/"
    - "\\.pdf$"
    - "\\.zip$"

  # 目次/一覧はDB保存しない（でもリンクは辿る）
  skip_save_title_regex:
    - "目次"
    - "一覧"
  skip_save_url_regex:
    - "/index\\.htm"
    - "/index2\\.htm"

kfs_saiketsu:
  enabled: true
  start_url: https://www.kfs.go.jp/service/JP/index.html
  delay_seconds: 1.2
  max_cases: 0
  include_youshi: false


chunking:
  max_chars: 1200
  overlap_chars: 200

embedding:
  model: intfloat/multilingual-e5-small
  normalize: true
  batch_size: 64

diff:
  enabled: false
